// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


export type Calendar = { slug: string; name: string | null; color: string | null; provider: string | null; account: string | null }

export type CalendarEvent = { id: string; recurring_event_id: string | null; summary: string; description: string | null; location: string | null; start: string; end: string; all_day: boolean; status: string; recurrence: Recurrence | null; master_recurrence: Recurrence | null; reminders: number[]; organizer: EventAttendee | null; attendees: EventAttendee[]; conference_url: string | null; calendar_slug: string }

/**
 * Input for creating an event
 */
export type CreateEventInput = { calendar_slug: string; summary: string; description: string | null; location: string | null; start: string; end: string; all_day: boolean; recurrence: Recurrence | null; reminders: number[] }

export type CredentialFieldInput = { id: string; value: string }

export type EventAttendee = { name: string | null; email: string; response_status: ResponseStatus | null }

export type Recurrence = { rrule: string; exdates: string[] }

export type ResponseStatus = "accepted" | "declined" | "tentative" | "needs-action"

/**
 * Input for updating an event
 */
export type UpdateEventInput = { id: string; calendar_slug: string; 
/**
 * If set and different from calendar_slug, moves the event to this calendar
 */
new_calendar_slug: string | null; summary: string; description: string | null; location: string | null; start: string; end: string; all_day: boolean; recurrence: Recurrence | null; reminders: number[] }

const ARGS_MAP = { 'caldir':'{"connect_provider":["provider_name"],"connect_provider_with_credentials":["provider_name","credentials"],"create_event":["input"],"delete_event":["calendar_slug","event_id"],"delete_recurring_series":["calendar_slug","uid"],"get_event":["calendar_slug","event_id"],"list_calendars":[],"list_events":["calendar_slugs","start","end"],"list_invites":["calendar_slugs"],"rsvp":["calendar_slug","event_id","response"],"sync":["calendar_slugs"],"update_event":["input"]}' }
export type Router = { "caldir": {connect_provider: (providerName: string) => Promise<Calendar[]>, 
connect_provider_with_credentials: (providerName: string, credentials: CredentialFieldInput[]) => Promise<Calendar[]>, 
create_event: (input: CreateEventInput) => Promise<CalendarEvent>, 
delete_event: (calendarSlug: string, eventId: string) => Promise<null>, 
delete_recurring_series: (calendarSlug: string, uid: string) => Promise<null>, 
get_event: (calendarSlug: string, eventId: string) => Promise<CalendarEvent | null>, 
list_calendars: () => Promise<Calendar[]>, 
list_events: (calendarSlugs: string[], start: string, end: string) => Promise<CalendarEvent[]>, 
list_invites: (calendarSlugs: string[]) => Promise<CalendarEvent[]>, 
rsvp: (calendarSlug: string, eventId: string, response: string) => Promise<null>, 
sync: (calendarSlugs: string[]) => Promise<null>, 
update_event: (input: UpdateEventInput) => Promise<null>} };


export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
