// This file has been generated by Specta. DO NOT EDIT.
import { createTauRPCProxy as createProxy, type InferCommandOutput } from "taurpc"

type TAURI_CHANNEL<T> = (response: T) => void

const ARGS_MAP = { "": '{"greet":["name"],"start_google_oauth":[]}' }
export type Router = { "": { greet: (name: string) => Promise<string>; start_google_oauth: () => Promise<string> } }

export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
