// Generated by just gen-types. Do not edit.

import type { CaldirSettings, ExternalTheme, OmarchyColors } from "./bindings"

export type AppEvent = { name: "caldir-config-changed"; payload: CaldirSettings } | { name: "calendars-changed"; payload: null } | { name: "events-changed"; payload: null } | { name: "event-deep-link-available"; payload: null } | { name: "rencal-config-changed"; payload: null } | { name: "system-tz-changed"; payload: string } | { name: "omarchy-theme-changed"; payload: OmarchyColors } | { name: "external-themes-changed"; payload: ExternalTheme[] } | { name: "menu-action"; payload: string } | { name: "theme-changed"; payload: string }

export type AppEventName = AppEvent["name"]
export type AppEventPayload<N extends AppEventName> = Extract<AppEvent, { name: N }>["payload"]
