//! The notification contract shared with the frontend. State changes still flow
//! through AppState's watch channels and state_bridge; other producers keep
//! ownership of their notifications. The enum envelope is for typing only:
//! native Tauri delivery sends its payload on its name.

use serde::Serialize;
use specta::Type;
use tauri::{Emitter, Runtime};

use crate::external_themes::ExternalTheme;
use crate::omarchy::OmarchyColors;
use crate::routes::caldir::CaldirSettings;

#[derive(Clone, Serialize, Type)]
#[serde(tag = "name", content = "payload", rename_all = "kebab-case")]
pub enum AppEvent {
    CaldirConfigChanged(CaldirSettings),
    CalendarsChanged(()),
    EventsChanged(()),
    EventDeepLinkAvailable(()),
    RencalConfigChanged(()),
    SystemTzChanged(String),
    OmarchyThemeChanged(OmarchyColors),
    ExternalThemesChanged(Vec<ExternalTheme>),
    #[cfg_attr(not(target_os = "macos"), allow(dead_code))]
    MenuAction(String),
    #[allow(dead_code)] // Emitted by the frontend only; still part of the contract.
    ThemeChanged(String),
}

impl AppEvent {
    /// Derive both transport arguments from serde, never a second dispatch table.
    pub fn emit<R: Runtime>(&self, app: &impl Emitter<R>) -> tauri::Result<()> {
        let envelope = serde_json::to_value(self)?;
        let name = envelope["name"]
            .as_str()
            .expect("AppEvent has a string tag");
        app.emit(name, &envelope["payload"])
    }
}

/// Called by the router in development, including the standalone generator.
#[cfg(debug_assertions)]
pub fn export_types() -> anyhow::Result<()> {
    use specta::{NamedType, TypeCollection};

    let mut types = TypeCollection::default();
    AppEvent::definition_named_data_type(&mut types);
    let body = specta_typescript::export::<AppEvent>(&Default::default())?;
    // Specta also lists transitive dependencies; import only the payload types
    // the union names. All of them are already exported by the RPC router.
    let mut imports: Vec<_> = types
        .into_iter()
        .filter(|(id, _)| *id != AppEvent::sid())
        .map(|(_, ty)| ty.name().to_string())
        .filter(|name| {
            body.split(|c: char| !c.is_alphanumeric() && c != '_')
                .any(|t| t == name)
        })
        .collect();
    imports.sort();
    std::fs::write(
        concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../src/rpc/events.generated.ts"
        ),
        format!(
            "// Generated by just gen-types. Do not edit.\n\nimport type {{ {} }} from \"./bindings\"\n\n{body}\n\nexport type AppEventName = AppEvent[\"name\"]\nexport type AppEventPayload<N extends AppEventName> = Extract<AppEvent, {{ name: N }}>[\"payload\"]\n",
            imports.join(", "),
        ),
    )?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::omarchy::OmarchyMode;
    use crate::routes::caldir::TimeFormat;
    use serde_json::{Value, json};

    #[test]
    fn notification_names_and_payloads_preserve_the_native_contract() {
        let settings = CaldirSettings {
            time_format: TimeFormat::H24,
            default_reminders: vec![5],
            default_calendar: Some("work".into()),
            calendar_dir: "~/caldir".into(),
        };
        let colors = OmarchyColors {
            mode: OmarchyMode::Dark,
            name: None,
            background: "#000000".into(),
            foreground: "#ffffff".into(),
            bright_foreground: "#ffffff".into(),
            accent: "#ff0000".into(),
            red: "#ff0000".into(),
            green: "#00ff00".into(),
            yellow: "#ffff00".into(),
            blue: "#0000ff".into(),
        };
        let themes = vec![ExternalTheme {
            id: "user:test".into(),
            name: "Test".into(),
            css: "--background: red".into(),
        }];
        let cases: Vec<(AppEvent, &str, Value)> = vec![
            (
                AppEvent::CaldirConfigChanged(settings.clone()),
                "caldir-config-changed",
                serde_json::to_value(settings).unwrap(),
            ),
            (
                AppEvent::CalendarsChanged(()),
                "calendars-changed",
                Value::Null,
            ),
            (AppEvent::EventsChanged(()), "events-changed", Value::Null),
            (
                AppEvent::EventDeepLinkAvailable(()),
                "event-deep-link-available",
                Value::Null,
            ),
            (
                AppEvent::RencalConfigChanged(()),
                "rencal-config-changed",
                Value::Null,
            ),
            (
                AppEvent::SystemTzChanged("Europe/London".into()),
                "system-tz-changed",
                json!("Europe/London"),
            ),
            (
                AppEvent::OmarchyThemeChanged(colors.clone()),
                "omarchy-theme-changed",
                serde_json::to_value(colors).unwrap(),
            ),
            (
                AppEvent::ExternalThemesChanged(themes.clone()),
                "external-themes-changed",
                serde_json::to_value(themes).unwrap(),
            ),
            (
                AppEvent::MenuAction("compose-event".into()),
                "menu-action",
                json!("compose-event"),
            ),
            (
                AppEvent::ThemeChanged("user:test".into()),
                "theme-changed",
                json!("user:test"),
            ),
        ];
        for (event, name, payload) in cases {
            assert_eq!(
                serde_json::to_value(event).unwrap(),
                json!({ "name": name, "payload": payload })
            );
        }
    }
}
